# Generated by Django 4.0.4 on 2022-05-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='list',
            new_name='list_id',
        ),
    ]
