# Generated by Django 4.0.4 on 2022-05-03 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_list_todoitem_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='finished',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
